import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signOut, getSession, GetSessionParams } from "next-auth/react";
import styles from "../styles/Home.module.css";
// import useRequireAuth from "../lib/useRequiredAuth";
const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>{`Seja bem vindo ${session?.user?.name}`}</h1>
        <button onClick={() => signOut()}>Logout</button>
      </div>
    </div>
  );
};

export default Home;
